export const BASE_URL: string = 'http://localhost:3005';
export const LOGIN: string = '/login';
export const PROFILE: string = 'profile';
export const SIGN_UP: string = '/signup';
export const PRODUCT: string = '/product';
export const CATEGORIES: string = '/categories';
export const FILTER: string = '/filter';
export const CART:string = '/cart';
export const ORDER:string = '/order'
export const TRENDING:string = '/trending-products';